services:
  - type: web
    name: mysql-db
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    autoDeploy: false
    envVars:
      - key: MYSQL_DATABASE
        value: learn
      - key: MYSQL_USER
        value: ak
      - key: MYSQL_PASSWORD
        value: ak@123
      - key: MYSQL_ROOT_PASSWORD
        value: akadmin@123
    ports:
      - port: 3306
        protocol: tcp
